services:
  laravel.test:
    image: wadedeilee/mylaravelapp:pokemon
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-80}:80'
    environment:
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: pokemon
      DB_USERNAME: wade
      DB_PASSWORD: Elvis790510

      TEST_DB_CONNECTION: mysql
      TEST_DB_HOST: mysql
      TEST_DB_PORT: 3306
      TEST_DB_DATABASE: my_testing_database
      TEST_DB_USERNAME: wade
      TEST_DB_PASSWORD: Elvis790510
    volumes:
      - '.:/var/www/html'
    networks:
      - sail
    depends_on:
      - mysql
  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3307}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: Elvis790510
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'pokemon'
      MYSQL_USER: 'wade'
      MYSQL_PASSWORD: Elvis790510
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no' # 已修正的缩进
    volumes: # 已修正的缩进
      - 'sail-mysql:/var/lib/mysql'
      - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
    networks: # 已修正的缩进
      - sail
    healthcheck: # 已修正的缩进
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s

  nginx:
    image: nginx:latest # 或者您需要的任何特定版本
    ports:
      - '8081:80' # 如果80端口已经被其他服务占用，您可以选择另一个端口
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf' # 如果您有自定义的nginx配置文件，您可以通过卷映射到容器中
    depends_on:
      - laravel.test # 如果nginx依赖于laravel.test服务，则需要这一行
    networks:
      - sail
networks:
  sail:
    driver: bridge
volumes:
  sail-mysql:
    driver: local

