openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/abilities:
    post:
      summary: ''
      operationId: postApiAbilities
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Ability
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: bwzumkgrpv
              required:
                - name
      security: []
  '/api/abilities/{ability_id}':
    patch:
      summary: ''
      operationId: patchApiAbilitiesAbility_id
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Ability
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: kgscaj
              required:
                - name
      security: []
    parameters:
      -
        in: path
        name: ability_id
        description: 'The ID of the ability.'
        example: 8
        required: true
        schema:
          type: integer
  /api/natures:
    post:
      summary: ''
      operationId: postApiNatures
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Nature
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: wpnxw
              required:
                - name
      security: []
  '/api/natures/{nature_id}':
    patch:
      summary: ''
      operationId: patchApiNaturesNature_id
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Nature
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: asppyprqpedkujpclxu
              required:
                - name
      security: []
    parameters:
      -
        in: path
        name: nature_id
        description: 'The ID of the nature.'
        example: 15
        required: true
        schema:
          type: integer
  /api/pokemons:
    post:
      summary: ''
      operationId: postApiPokemons
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Pokemons
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must not be greater than 15 characters.'
                  example: immmyymtppjp
                race_id:
                  type: integer
                  description: ''
                  example: 8
                ability_id:
                  type: integer
                  description: ''
                  example: 1
                nature_id:
                  type: integer
                  description: ''
                  example: 17
                level:
                  type: integer
                  description: 'Must be at least 1. Must not be greater than 100.'
                  example: 24
                skills:
                  type: array
                  description: ''
                  example:
                    - 15
                  items:
                    type: integer
              required:
                - name
                - race_id
                - ability_id
                - nature_id
                - level
      security: []
  '/api/pokemons/{pokemon_id}':
    patch:
      summary: ''
      operationId: patchApiPokemonsPokemon_id
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Pokemons
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'The name of the pokemon. Must not be greater than 15 characters.'
                  example: Pikachu
                race_id:
                  type: integer
                  description: 'The ID of the race for the pokemon.'
                  example: 1
                ability_id:
                  type: integer
                  description: 'The ID of the ability for the pokemon.'
                  example: 1
                nature_id:
                  type: integer
                  description: 'The ID of the nature for the pokemon.'
                  example: 1
                level:
                  type: integer
                  description: 'The level for the pokemon. Must be at least 1. Must not be greater than 100.'
                  example: 1
                skills:
                  type: array
                  description: ''
                  example: null
                  items:
                    type: string
      security: []
    delete:
      summary: ''
      operationId: deleteApiPokemonsPokemon_id
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Pokemons
      security: []
    parameters:
      -
        in: path
        name: pokemon_id
        description: 'The ID of the pokemon.'
        example: 5
        required: true
        schema:
          type: integer
  '/api/pokemons/{pokemon_id}/evolution':
    put:
      summary: ''
      operationId: putApiPokemonsPokemon_idEvolution
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Pokemons
      security: []
    parameters:
      -
        in: path
        name: pokemon_id
        description: 'The ID of the pokemon.'
        example: 4
        required: true
        schema:
          type: integer
tags:
  -
    name: Ability
    description: 'Operations related to abilities.'
  -
    name: Nature
    description: 'Operations related to natures.'
  -
    name: Pokemons
    description: 'Operations related to pokemons.'
